# Generated by Django 4.0.5 on 2022-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='voted_already',
            field=models.BooleanField(default=False),
        ),
    ]
